pull_request_rules:
  - name: Automatic merge for depfu pull requests
    conditions:
      - author=depfu[bot]
      - base=master
      - title~=\(patch\)$
    actions:
      merge:
        method: merge